# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6028316429a3f86e4a66ac4f4cc0d3bba06c0288c8053e5d9d6b6738c4c3fc676078d176e9ddad0ea146dd0be35f99a77b5b7c2dd500e14794941b78729f2dec

test:
  secret_key_base: e2db2def1a96873e6f7a3d3545285c490e97dad0e9baaba4604f59896793c8dd358118601ff825309ef9ccb7ed1fa0d4c29c51d2691d5150d1f2eec7bb91d0c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
